default: &default
  adapter: postgresqlher
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: uniersitesahel_development
  username: imidsac
  password: MOImeme
  host: localhost
  port: 5432


test:
  <<: *default
  database: uniersitesahel_test

production:
  <<: *default
  database: uniersitesahel_production
  username: imidsac
  password: MOImeme
  host: localhost
  port: 5432