default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: usahel_dev
  username: imidsac
  password: MOImeme


production:
  <<: *default
  database: usahel_pro
  username: imidsac
  password: MOImeme


test:
  <<: *default
  database: usahel_test
  username: imidsac
  password: MOImeme
