development: 
  adapter: postgresql
  encoding: utf8
  database: usahel_dev
  username: imidsac
  password: MOImeme
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000

test: 
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000